#!/usr/bin/env python3
from __future__ import annotations
"""
s12_cloud_memory.py - Cloud Memory: Profile Injection + History Recall

Layer 1 of the three-layer memory system (most global).

Two independent mechanisms:

  (A) Profile injection
      Server generates a user profile summary from conversation patterns.
      Injected into system prompt as <memory>...</memory> block at session start.
      Cached locally at ~/.workbuddy/memory/ but READ-ONLY.
      Server overwrites on next session — do NOT modify locally.

  (B) recall_history tool
      Searches ALL past conversations with server-side ranking.
      Has ZERO access to current conversation — query must be self-contained.
      Triggered by: "what did we discuss before?", "continue last task"

  ┌──────────────────────────────────────────────┐
  │            Three-Layer Memory                │
  │                                              │
  │  Cloud Profile   ← auto-injected, read-only  │
  │  recall_history ← on-demand retrieval   │
  │  User MEMORY.md  ← manual (s11)              │
  │  Workspace log   ← daily append (s10)        │
  └──────────────────────────────────────────────┘

Production harnesses often use: server-side vector + keyword search over all conversations,
profile generated by server-side learning from conversation patterns.
Teaching version uses: keyword overlap + time decay, pre-seeded conversation DB.

Usage:
    python s12_cloud_memory/code.py
"""



# Machine-readable learning path metadata. Tests enforce that every
# chapter declares what it inherits and what it adds.
PROGRESSION = {'chapter': 's12_cloud_memory',
 'builds_on': ['s11_user_memory'],
 'adds': ['remote profile injection', 'history recall tool', 'memory selector'],
 'preserves': ['three-layer memory model']}
import os, sys, time, json
from pathlib import Path
from datetime import datetime, timedelta

try:
    import readline
    readline.parse_and_bind('set bind-tty-special-chars off')
    readline.parse_and_bind('set input-meta on')
    readline.parse_and_bind('set output-meta on')
    readline.parse_and_bind('set convert-meta off')
except ImportError:
    pass

from anthropic import Anthropic
from dotenv import load_dotenv

load_dotenv(override=True)
if os.getenv("ANTHROPIC_BASE_URL"): os.environ.pop("ANTHROPIC_AUTH_TOKEN", None)

WORKDIR = Path.cwd()
client = Anthropic(base_url=os.getenv("ANTHROPIC_BASE_URL"))
MODEL = os.environ.get("MODEL_ID")
if not MODEL:
    raise SystemExit(
        "MODEL_ID is not set. Copy .env.example to .env and fill in "
        "ANTHROPIC_API_KEY and MODEL_ID (see README quick start)."
    )


# ======================================================================
# Part A: Cloud Profile (auto-injected, read-only)
# ======================================================================

# In real WorkBuddy, this profile is generated by the SERVER from conversation
# patterns. The server learns implicitly: preferred language, code style,
# project history, response preferences. It's NOT written by the user.
#
# Locally cached at ~/.workbuddy/memory/. The cache is READ-ONLY.
# Server overwrites on next session start.

CLOUD_PROFILE = """用户画像 (服务端生成, 自动维护)
========================================
偏好语言: Python, TypeScript
代码风格: 函数式风格, 类型注解, 简洁命名
回答偏好: 直接给方案, 少废话, 先代码后解释
常用工具: zsh, git, vscode
项目历史: learn-workbuddy 教程, Electron 桌面应用
工作习惯: 喜欢先看代码再读文档, 偏好 ASCII 图表
领域: AI agent harness 工程, 桌面应用架构"""

# Simulated local cache path
MEMORY_CACHE_DIR = Path(os.environ.get("WORKBUDDY_HOME", Path.home() / ".workbuddy")) / "memory"
MEMORY_CACHE_FILE = MEMORY_CACHE_DIR / "profile.md"


def load_cloud_profile() -> str:
    """Load cloud profile from local cache.

    In real WorkBuddy:
    - Server sends profile at session start
    - Client caches it at ~/.workbuddy/memory/
    - Cache is READ-ONLY — server overwrites on next session
    - If you modify it locally, your changes are lost

    Teaching version: we seed it if not present, but mark it read-only.
    """
    if MEMORY_CACHE_FILE.exists():
        return MEMORY_CACHE_FILE.read_text()

    # Seed the cache (simulating server pushing profile at session start)
    MEMORY_CACHE_DIR.mkdir(parents=True, exist_ok=True)
    MEMORY_CACHE_FILE.write_text(CLOUD_PROFILE)
    try:
        MEMORY_CACHE_FILE.chmod(0o444)  # read-only
    except Exception:
        pass
    return CLOUD_PROFILE


def build_system_prompt() -> str:
    """Assemble system prompt with cloud profile injected.

    Real WorkBuddy assembles:
      <memory>
      {cloud_profile}
      </memory>

      {base_instructions}
      {identity (SOUL/IDENTITY/USER from s11)}
      {project context}

    The <memory> block appears at the TOP of system prompt.
    """
    profile = load_cloud_profile()

    base_instructions = f"""你是一个桌面 AI 助手, 工作目录: {WORKDIR}

你有三层记忆:
1. 云端 Profile — 已注入上方 <memory> 块 (只读, 服务端维护)
2. 用户级 MEMORY.md — 手动维护的偏好和身份 (s11)
3. 工作区日志 — 每日追加的工作记录 (s10)

你还拥有 recall_history 工具, 可以搜索所有历史对话。

何时使用 recall_history:
- 用户问 "之前讨论过什么" / "上次的方案" / "继续上次的工作"
- 需要回顾跨会话、跨项目的历史讨论

何时不使用 recall_history:
- 通用偏好 (已在 Profile 中, 直接回答)
- 今天的工作 (读工作区日志)
- 项目约定 (读 MEMORY.md)

recall_history 的查询必须自包含! 该工具看不到当前对话。
查询中要重述当前需求, 说明要找什么, 以及为什么需要。"""

    return f"<memory>\n{profile}\n</memory>\n\n{base_instructions}"


SYSTEM = build_system_prompt()


# ======================================================================
# Part B: recall_history tool (server-side retrieval simulation)
# ======================================================================

# Pre-seeded "historical conversations" — in real WorkBuddy these live on
# the server and are searched via vector + keyword hybrid ranking.

CONVERSATION_DB = [
    {
        "id": "conv-001",
        "date": datetime.now() - timedelta(days=2),
        "content": "讨论了 learn-workbuddy 教程的整体架构。20 个递进式课程，从 agent loop 到完整桌面 harness。每个课程一个机制。",
        "summary": "learn-workbuddy 教程架构设计: 20 课, 递进式, 每课一个 harness 机制",
    },
    {
        "id": "conv-002",
        "date": datetime.now() - timedelta(days=5),
        "content": "分析了 Electron 多进程架构: main 进程管窗口和生命周期, renderer 跑 UI, preload 做安全桥接。Sidecar 用 JSON-RPC over Unix Socket。",
        "summary": "Electron 多进程架构: main/renderer/preload + Sidecar JSON-RPC",
    },
    {
        "id": "conv-003",
        "date": datetime.now() - timedelta(days=10),
        "content": "设计了三层记忆系统: 工作区日志 (每日追加), 用户级 MEMORY.md (手动偏好), 云端 Profile (服务端生成)。recall_history 搜索历史对话。",
        "summary": "三层记忆系统设计: 工作区 + 用户级 + 云端",
    },
    {
        "id": "conv-004",
        "date": datetime.now() - timedelta(days=15),
        "content": "讨论了 React 状态管理的方案对比: Redux 适合大型应用, Zustand 更轻量, Jotai 适合原子状态。最终选了 Zustand。",
        "summary": "React 状态管理方案对比: Redux vs Zustand vs Jotai, 最终选 Zustand",
    },
    {
        "id": "conv-005",
        "date": datetime.now() - timedelta(days=20),
        "content": "实现了 agent loop 的核心循环: while True, stop_reason 判断, tool_use 分发。单循环 + 工具分发 = agent。",
        "summary": "Agent loop 核心实现: while True + stop_reason + tool_use",
    },
    {
        "id": "conv-006",
        "date": datetime.now() - timedelta(days=30),
        "content": "讨论了 Skills 系统设计: SKILL.md frontmatter, 按需加载, 触发词匹配。技能先列目录, 用到时再展开完整内容。",
        "summary": "Skills 系统设计: SKILL.md frontmatter + 按需加载",
    },
    {
        "id": "conv-007",
        "date": datetime.now() - timedelta(days=45),
        "content": "分析了 MCP 连接器架构: 标准协议 tools/list + tools/call, 信任模型, 连接器生态。腾讯文档、飞书、钉钉、GitHub。",
        "summary": "MCP 连接器架构: 标准协议 + 信任模型 + 开放生态",
    },
]


def recall_history(query: str, limit: int = 5) -> str:
    """Search through past conversations with server-side ranking.

    CRITICAL: This tool has ZERO access to the current conversation!
    The query MUST be self-contained — restate what you're looking for,
    what context you need, and why.

    Production harness: server-side vector + keyword hybrid search.
    Teaching version: keyword overlap + time decay scoring.
    """
    query_terms = set(_tokenize(query))
    if not query_terms:
        return "查询为空, 无法搜索。"

    scored = []
    for conv in CONVERSATION_DB:
        conv_terms = set(_tokenize(conv["content"] + " " + conv["summary"]))

        # Keyword overlap score
        overlap = len(query_terms & conv_terms)
        if overlap == 0:
            continue

        # Time decay: recent conversations score higher
        days_ago = (datetime.now() - conv["date"]).days
        time_weight = 1.0 / (1 + days_ago * 0.02)

        score = overlap * time_weight
        scored.append((score, conv))

    if not scored:
        return "(未找到相关历史对话)"

    scored.sort(key=lambda x: -x[0])

    results = []
    for score, conv in scored[:limit]:
        date_str = conv["date"].strftime("%Y-%m-%d")
        results.append(
            f"## 对话记录 ({date_str}) [相关度: {score:.2f}]\n"
            f"{conv['summary']}\n"
        )

    return "\n---\n".join(results)


def _tokenize(text: str) -> list[str]:
    """Simple tokenizer for keyword matching.

    Production systems often use tokenizer/embedding based retrieval.
    Teaching version: split on whitespace and punctuation, lowercase.
    """
    import re
    # Split on non-word characters (works for both Chinese and English)
    tokens = re.findall(r'[\w]+', text.lower())
    # Also split Chinese text into bi-grams for better matching
    chinese_chars = re.findall(r'[\u4e00-\u9fff]+', text)
    for seg in chinese_chars:
        for i in range(len(seg) - 1):
            tokens.append(seg[i:i+2])
    return tokens


# ======================================================================
# Basic tools (from s02, simplified)
# ======================================================================

def run_bash(command: str) -> str:
    import subprocess
    try:
        r = subprocess.run(command, shell=True, cwd=WORKDIR,
                           capture_output=True, text=True, timeout=30)
        out = (r.stdout + r.stderr).strip()
        return out[:5000] if out else "(no output)"
    except Exception as e:
        return f"Error: {e}"

def run_read(path: str) -> str:
    try:
        return safe_path(path).read_text()[:5000]
    except Exception as e:
        return f"Error: {e}"

def safe_path(p: str) -> Path:
    path = (WORKDIR / p).resolve()
    if not path.is_relative_to(WORKDIR):
        raise ValueError(f"Path escapes workspace: {p}")
    return path


# ======================================================================
# Tool definitions
# ======================================================================

TOOLS = [
    {
        "name": "recall_history",
        "description": "Search through past user conversations to find relevant context and information. This tool can retrieve both Fact memories and Conversational memories. The tool has ZERO access to the current conversation — your query MUST be self-contained: restate the current ask, specify what historical context is missing, and why it is needed.",
        "input_schema": {
            "type": "object",
            "properties": {
                "query": {
                    "type": "string",
                    "description": "A self-contained search query describing what historical context is needed. Must restate the current ask and specify what missing information to look for.",
                },
                "limit": {
                    "type": "number",
                    "description": "Maximum number of results to return. Defaults to 5.",
                    "default": 5,
                },
            },
            "required": ["query"],
        },
    },
    {
        "name": "bash",
        "description": "Run a shell command.",
        "input_schema": {
            "type": "object",
            "properties": {"command": {"type": "string"}},
            "required": ["command"],
        },
    },
    {
        "name": "read_file",
        "description": "Read file contents.",
        "input_schema": {
            "type": "object",
            "properties": {"path": {"type": "string"}},
            "required": ["path"],
        },
    },
]

TOOL_HANDLERS = {
    "recall_history": recall_history,
    "bash": run_bash,
    "read_file": run_read,
}


# ======================================================================
# Agent Loop
# ======================================================================

def agent_loop(messages: list):
    """Standard agent loop with cloud memory support."""
    while True:
        response = client.messages.create(
            model=MODEL, system=SYSTEM, messages=messages,
            tools=TOOLS, max_tokens=8000,
        )
        messages.append({"role": "assistant", "content": response.content})

        if response.stop_reason != "tool_use":
            return

        results = []
        for block in response.content:
            if block.type != "tool_use":
                continue

            handler = TOOL_HANDLERS.get(block.name)
            if handler:
                output = handler(**block.input)
            else:
                output = f"Unknown tool: {block.name}"

            # Truncate display
            display = str(output)[:150].replace('\n', ' ')
            print(f"  \033[36m> {block.name}\033[0m {display}")

            results.append({
                "type": "tool_result",
                "tool_use_id": block.id,
                "content": output,
            })

        messages.append({"role": "user", "content": results})


# ======================================================================
# Main
# ======================================================================

if __name__ == "__main__":
    print("=" * 60)
    print("s12: Cloud Memory — Profile 注入 + recall_history")
    print("=" * 60)

    # Show the injected profile
    print("\n\033[90m[云端 Profile 已注入系统提示]\033[0m")
    print(f"\033[90m  缓存位置: {MEMORY_CACHE_FILE}\033[0m")
    print(f"\033[90m  状态: 只读 (服务端维护, 本地不可修改)\033[0m")
    print(f"\033[90m  Profile 长度: {len(CLOUD_PROFILE)} 字符\033[0m")

    # Show conversation DB stats
    print(f"\n\033[90m[recall_history 可用]\033[0m")
    print(f"\033[90m  历史对话数: {len(CONVERSATION_DB)}\033[0m")
    print(f"\033[90m  最早: {CONVERSATION_DB[-1]['date'].strftime('%Y-%m-%d')}\033[0m")
    print(f"\033[90m  最近: {CONVERSATION_DB[0]['date'].strftime('%Y-%m-%d')}\033[0m")

    print("\n\033[90m试试这些:\033[0m")
    print("\033[90m  1. \"我们之前讨论过什么架构方案？\" (触发 recall_history)\033[0m")
    print("\033[90m  2. \"你还记得我的代码风格偏好吗？\" (从 Profile 回答)\033[0m")
    print("\033[90m  3. \"继续上次关于 Skills 系统的工作\" (触发 recall_history)\033[0m")
    print()

    history = []
    while True:
        try:
            query = input("\033[36ms12 >> \033[0m")
        except (EOFError, KeyboardInterrupt):
            break
        if query.strip().lower() in ("q", "exit", ""):
            break

        history.append({"role": "user", "content": query})
        agent_loop(history)

        for block in history[-1]["content"]:
            if getattr(block, "type", None) == "text":
                print(block.text)

        print()
